package model

type ListSippersLogin struct {
	Name string `db:"name"`
}

type Sippers struct {
	Id                string `db:"ID"`
	Name              string `db:"NAME"`
	IpAddr            string `db:"IPADDR"`
	Port              string `db:"PORT"`
	RegSeconds        string `db:"REGSECONDS"`
	DefaultUser       string `db:"DEFAULTUSER"`
	FullContact       string `db:"FULLCONTACT"`
	RegServer         string `db:"REGSERVER"`
	UserAgent         string `db:"USERAGENT"`
	LastMS            string `db:"LASTMS"`
	Host              string `db:"HOST"`
	Type              string `db:"TYPE"`
	Context           string `db:"CONTEXT"`
	Permit            string `db:"PERMIT"`
	Deny              string `db:"DENY"`
	Secret            string `db:"SECRET"`
	MD5Secret         string `db:"MD5SECRET"`
	RemoteSecret      string `db:"REMOTESECRET"`
	Transport         string `db:"TRANSPORT"`
	DtmFMode          string `db:"DTMFMODE"`
	DirectMedia       string `db:"DIRECTMEDIA"`
	Nat               string `db:"NAT"`
	CallGroup         string `db:"CALLGROUP"`
	PickUpGroup       string `db:"PICKUPGROUP"`
	Language          string `db:"LANGUAGE"`
	Disallow          string `db:"DISALLOW"`
	Allow             string `db:"ALLOW"`
	Insecure          string `db:"INSECURE"`
	Trustrprid        string `db:"TRUSTRPID"`
	ProgressInBand    string `db:"PROGRESSINBAND"`
	PromisCredir      string `db:"PROMISCREDIR"`
	UseClientCode     string `db:"USECLIENTCODE"`
	AccountCode       string `db:"ACCOUNTCODE"`
	Setvar            string `db:"SETVAR"`
	CallerId          string `db:"CALLERID"`
	AmaFlags          string `db:"AMAFLAGS"`
	CallCounter       string `db:"CALLCOUNTER"`
	BusyLevel         string `db:"BUSYLEVEL"`
	AllowOverLap      string `db:"ALLOWOVERLAP"`
	AllowSubscribe    string `db:"ALLOWSUBSCRIBE"`
	VidoSupport       string `db:"VIDEOSUPPORT"`
	MaxCallBitrate    string `db:"MAXCALLBITRATE"`
	RFC2833Compensate string `db:"RFC2833COMPENSATE"`
	MailBox           string `db:"MAILBOX"`
	SessionTimers     string `db:"SESSION-TIMERS"`
	SessionExpires    string `db:"SESSION-EXPIRES"`
	SessionMinse      string `db:"SESSION-MINSE"`
	SessionRefresher  string `db:"SESSION-REFRESHER"`
	T38prUserTPSourse string `db:"T38PT_USERTPSOURCE"`
	RegExten          string `db:"REGEXTEN"`
	FromDomain        string `db:"FROMDOMAIN"`
	FromUser          string `db:"FROMUSER"`
	Qualify           string `db:"QUALIFY"`
	DefaultTip        string `db:"DEFAULTIP"`
	RtpTimeout        string `db:"RTPTIMEOUT"`
	RtpHoldTimeout    string `db:"RTPHOLDTIMEOUT"`
	SendRpid          string `db:"SENDRPID"`
	OutBoundProxy     string `db:"OUTBOUNDPROXY"`
	CallBackExtension string `db:"CALLBACKEXTENSION"`
	Timert1           string `db:"TIMERT1"`
	TimerB            string `db:"TIMERB"`
	QualifyFreq       string `db:"QUALIFYFREQ"`
	ConstantSsrc      string `db:"CONSTANTSSRC"`
	ContactPermit     string `db:"CONTACTPERMIT"`
	ContactDeny       string `db:"CONTACTDENY"`
	UseReqPhone       string `db:"USEREQPHONE"`
	TextSupport       string `db:"TEXTSUPPORT"`
	FaxDetect         string `db:"FAXDETECT"`
	BuggyMwi          string `db:"BUGGYMWI"`
	Auth              string `db:"AUTH"`
	FullName          string `db:"FULLNAME"`
	TrunkName         string `db:"TRUNKNAME"`
	CIDNumber         string `db:"CID_NUMBER"`
	CallIngpres       string `db:"CALLINGPRES"`
	MohinTerpet       string `db:"MOHINTERPRET"`
	MohSuggest        string `db:"MOHSUGGEST"`
	ParkingLot        string `db:"PARKINGLOT"`
	HasVoiceMail      string `db:"HASVOICEMAIL"`
	SubscribeMWI      string `db:"SUBSCRIBEMWI"`
	Vmexten           string `db:"VMEXTEN"`
	AutoFraming       string `db:"AUTOFRAMING"`
	RtpKeepAlive      string `db:"RTPKEEPALIVE"`
	CallLimit         string `db:"CALL_LIMIT"`
	G726NonStandard   string `db:"G726NONSTANDARD"`
	IgnoreSDPVersion  string `db:"IGNORESDPVERSION"`
	AllowTransfer     string `db:"ALLOWTRANSFER"`
	Dynamic           string `db:"DYNAMIC"`
	Path              string `db:"PATH"`
	SupportPath       string `db:"SUPPORTPATH"`
	CanReinvite       string `db:"CANREINVITE"`
	Avpf              string `db:"AVPF"`
	ForceAvp          string `db:"FORCE_AVP"`
	IceSupport        string `db:"ICESUPPORT"`
	RtcpMux           string `db:"RTCP_MUX"`
	Encryption        string `db:"ENCRYPTION"`
	DtlsEnable        string `db:"DTLSENABLE"`
	DtlsVerify        string `db:"DTLSVERIFY"`
	DtlsCertfile      string `db:"DTLSCERTFILE"`
	DtlsPrivateKey    string `db:"DTLSPRIVATEKEY"`
	DtlsSetup         string `db:"DTLSSETUP"`
	DtlsRekey         string `db:"DTLSREKEY"`
}
